import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ThemeProvider } from "~/components/theme-provider"
import Footer from "~/components/Footer";
import { Toaster } from "~/components/ui/sonner"

export const metadata: Metadata = {
	title: "ResumeLens.AI",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
			<body className="min-h-screen flex flex-col">
				<ThemeProvider
          		  attribute="class"
          		  defaultTheme="system"
          		  enableSystem
          		  disableTransitionOnChange
          		>
					<main className="min-h-screen bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white px-6 md:px-20 pt-24 pb-10 flex-grow selection:bg-indigo-600 selection:text-white dark:selection:bg-amber-400 dark:selection:text-black">
						{children}
						<Footer />
					</main>
					<Toaster richColors closeButton />
				</ThemeProvider>
			</body>
		</html>
	);
}
